export type Lang = "EN" | "UA";

export const contacts = [
  {
    id: "daniel",
    name: "Daniel Kovalenko",
    initials: "DK",
    note: "Updated delivery terms",
    time: "15:23",
    tone: "blue",
  },
  {
    id: "anna",
    name: "Anna Petrova",
    initials: "AP",
    note: "Thank you, see you Friday",
    time: "14:48",
    tone: "rose",
  },
  {
    id: "sophia",
    name: "Sophia Chen",
    initials: "SC",
    note: "Sent a document",
    time: "13:17",
    tone: "violet",
  },
  { id: "mark", name: "Mark Ellis", initials: "ME", note: "Voice message", time: "Yesterday", tone: "slate" },
] as const;

export const conversation = {
  EN: {
    incoming: "Hi. Can you confirm the new price and exact delivery time today?",
    answer:
      "Yes. I reviewed the updated terms. I’ll send the final price and confirmed delivery time before 18:00.",
    placeholder: "Message Daniel",
    today: "Today",
    online: "online",
    messages: "Messages",
    search: "Search",
  },
  UA: {
    incoming: "Привіт. Чи можеш сьогодні підтвердити нову ціну і точний термін доставки?",
    answer:
      "Так. Я перевірив оновлені умови. До 18:00 надішлю фінальну ціну й підтверджений термін доставки.",
    placeholder: "Повідомлення для Daniel",
    today: "Сьогодні",
    online: "онлайн",
    messages: "Повідомлення",
    search: "Пошук",
  },
} as const;

export type KeySpec = { label: string; sub?: string; units?: number; kind?: "function" | "arrow" };

export const keyboardRows: readonly KeySpec[][] = [
  [
    { label: "esc", kind: "function", units: 1.25 },
    { label: "F1", sub: "☀", kind: "function" },
    { label: "F2", sub: "☀", kind: "function" },
    { label: "F3", sub: "▱", kind: "function" },
    { label: "F4", sub: "⌕", kind: "function" },
    { label: "F5", sub: "◖", kind: "function" },
    { label: "F6", sub: "◗", kind: "function" },
    { label: "F7", sub: "◀", kind: "function" },
    { label: "F8", sub: "▶", kind: "function" },
    { label: "F9", sub: "▶", kind: "function" },
    { label: "F10", sub: "◁", kind: "function" },
    { label: "F11", sub: "▽", kind: "function" },
    { label: "F12", sub: "△", kind: "function" },
    { label: "●", kind: "function", units: 1.15 },
  ],
  [
    { label: "`", sub: "~" },
    { label: "1", sub: "!" },
    { label: "2", sub: "@" },
    { label: "3", sub: "#" },
    { label: "4", sub: "$" },
    { label: "5", sub: "%" },
    { label: "6", sub: "^" },
    { label: "7", sub: "&" },
    { label: "8", sub: "*" },
    { label: "9", sub: "(" },
    { label: "0", sub: ")" },
    { label: "-", sub: "_" },
    { label: "=", sub: "+" },
    { label: "delete", units: 1.75 },
  ],
  [
    { label: "tab", units: 1.55 },
    { label: "Q" },
    { label: "W" },
    { label: "E" },
    { label: "R" },
    { label: "T" },
    { label: "Y" },
    { label: "U" },
    { label: "I" },
    { label: "O" },
    { label: "P" },
    { label: "[", sub: "{" },
    { label: "]", sub: "}" },
    { label: "\\", sub: "|", units: 1.2 },
  ],
  [
    { label: "caps lock", units: 1.82 },
    { label: "A" },
    { label: "S" },
    { label: "D" },
    { label: "F" },
    { label: "G" },
    { label: "H" },
    { label: "J" },
    { label: "K" },
    { label: "L" },
    { label: ";", sub: ":" },
    { label: "'", sub: '"' },
    { label: "return", units: 1.92 },
  ],
  [
    { label: "shift", units: 2.35 },
    { label: "Z" },
    { label: "X" },
    { label: "C" },
    { label: "V" },
    { label: "B" },
    { label: "N" },
    { label: "M" },
    { label: ",", sub: "<" },
    { label: ".", sub: ">" },
    { label: "/", sub: "?" },
    { label: "shift", units: 2.45 },
  ],
  [
    { label: "fn", sub: "◉", units: 1.15 },
    { label: "control", sub: "⌃", units: 1.22 },
    { label: "option", sub: "⌥", units: 1.28 },
    { label: "command", sub: "⌘", units: 1.52 },
    { label: "", units: 5.25 },
    { label: "command", sub: "⌘", units: 1.52 },
    { label: "option", sub: "⌥", units: 1.28 },
    { label: "◀", kind: "arrow" },
    { label: "▲", kind: "arrow" },
    { label: "▼", kind: "arrow" },
    { label: "▶", kind: "arrow" },
  ],
] as const;
