"use client";

import { AnimatePresence, motion, useReducedMotion, useScroll, useSpring } from "framer-motion";
import { Activity, ArrowRight, CalendarDays, Check, CircleStop, Database, Edit3, History, Link2, Mail, Menu, Pause, Play, RotateCcw, Send, ShieldCheck, Sparkles, Trash2, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getCurrentProfile } from "@/lib/auth";
import { useLang, type Lang } from "@/lib/i18n/lang-store";
import styles from "./SecondPresenceLanding.module.css";

const text = {
  EN: {
    nav:["Product","How it works","Memory","Autopilot","Security"], login:"Log in", create:"Create your Altr",
    hero:["You cannot be everywhere.","Altr can."], subtitle:"Altr learns how you communicate, remembers what matters and becomes your controlled second presence online.", action:"See it in action", trust:"Your identity. Your rules. Your final decision.",
    demo:{incoming:"Hey, are we still moving forward with the partnership?", steps:["Recognizing person","Retrieving shared history","Previous agreement found","Applying your communication style","Response prepared"], context:"You discussed pricing 12 days ago. They were waiting for your updated proposal.", reply:"Yes. I’ve reviewed the latest terms. I’ll send you the updated proposal today before 18:00.", approve:"Approve",edit:"Edit",ignore:"Ignore",replay:"Replay demo"},
    presence:["Your time is limited.","Your presence no longer has to be."], presenceBody:"Altr monitors the conversations you connect, prepares the next action and brings important decisions back to you.", status:["3 conversations monitored","1 reply awaiting approval","2 routine messages handled","No critical risks detected"],
    memoryTitle:"Every conversation becomes part of the system.", memoryNote:"Altr stores only information you allow. Every memory can be reviewed, edited or deleted.",
    voice:["Not an AI voice.","Your voice."], voiceNote:"Altr adds more than tone. It adds relationship history, context and concrete commitments.",
    autopilot:"Decide what Altr can decide.", modes:["Draft","Controlled","Autopilot"], modeBodies:["Altr prepares replies. Nothing is sent without approval.","Altr handles approved routine scenarios and sends important decisions to you.","Altr manages selected conversations within strict limits defined by you."],
    howTitle:"A personal system that compounds with every approved decision.", how:["Connect","Learn","Prepare","Approve","Compound"],
    security:["Your second presence.","Under your authority."], securityBody:"Altr can act for you. It never owns the final decision.",
    dashboard:"A command center for your second presence.", integrations:"Connect only what Altr is allowed to understand.",
    pricing:"Start with one presence. Expand when the system earns more responsibility.", month:"/month", personal:"Create your Altr", operator:"Become an Operator",
    final:["Build the version of you","that never loses context."], finalBody:"Create a second digital presence that remembers, prepares and acts within the boundaries you define.", remain:"You remain in control.",
  },
  UA: {
    nav:["Продукт","Як це працює","Пам’ять","Автопілот","Безпека"], login:"Увійти", create:"Створити свій Altr",
    hero:["Ти не можеш бути всюди.","Altr може."], subtitle:"Altr вивчає, як ти спілкуєшся, пам’ятає важливе й стає твоєю контрольованою другою присутністю онлайн.", action:"Подивитися в дії", trust:"Твоя особистість. Твої правила. Твоє фінальне рішення.",
    demo:{incoming:"Привіт, ми все ще рухаємося далі щодо партнерства?", steps:["Розпізнає співрозмовника","Піднімає спільну історію","Знаходить домовленість","Застосовує твій стиль","Готує відповідь"], context:"Ви обговорювали ціну 12 днів тому. Вони чекали на твою оновлену пропозицію.", reply:"Так. Я переглянув останні умови. Сьогодні до 18:00 надішлю оновлену пропозицію.", approve:"Погодити",edit:"Редагувати",ignore:"Ігнорувати",replay:"Повторити демо"},
    presence:["Твій час обмежений.","Твоя присутність — уже ні."], presenceBody:"Altr стежить за підключеними розмовами, готує наступну дію й повертає тобі важливі рішення.", status:["3 розмови під наглядом","1 відповідь очікує погодження","2 рутинні повідомлення опрацьовано","Критичних ризиків не виявлено"],
    memoryTitle:"Кожна розмова стає частиною системи.", memoryNote:"Altr зберігає лише дозволену тобою інформацію. Кожен спогад можна переглянути, змінити або видалити.",
    voice:["Не голос AI.","Твій голос."], voiceNote:"Altr додає не лише тон. Він додає історію стосунків, контекст і конкретні зобов’язання.",
    autopilot:"Виріши, що Altr може вирішувати.", modes:["Чернетка","Контрольований","Автопілот"], modeBodies:["Altr готує відповіді. Нічого не надсилається без погодження.","Altr обробляє дозволені рутинні сценарії, а важливі рішення повертає тобі.","Altr веде вибрані розмови в межах суворих правил, які визначаєш ти."],
    howTitle:"Персональна система, яка посилюється з кожним погодженим рішенням.", how:["Підключення","Навчання","Підготовка","Погодження","Накопичення"],
    security:["Твоя друга присутність.","Під твоєю владою."], securityBody:"Altr може діяти за тебе. Він ніколи не забирає фінальне рішення.",
    dashboard:"Командний центр твоєї другої присутності.", integrations:"Підключай лише те, що Altr дозволено розуміти.",
    pricing:"Почни з однієї присутності. Розширюй, коли система заслужить більше відповідальності.", month:"/місяць", personal:"Створити свій Altr", operator:"Стати Operator",
    final:["Створи версію себе,","яка ніколи не втрачає контекст."], finalBody:"Створи другу цифрову присутність, яка пам’ятає, готує й діє в межах, визначених тобою.", remain:"Ти залишаєшся головним.",
  },
} as const;

const memories = [["Relationship","2 years"],["Last conversation","4 days ago"],["Current topic","New product pricing"],["Open promise","Send updated specification"],["Preferred tone","Direct and professional"],["Important detail","Requires exact quantities"]];
const autoYes=["Meeting confirmations","Standard customer questions","Follow-ups","Messages from selected contacts","Basic status updates"];
const autoNo=["Payments","Prices and discounts","Legal agreements","Conflicts","Sensitive personal topics","Final promises and commitments"];
const controls=[Pause,Database,Edit3,Trash2,History,Link2,Activity,CircleStop,Trash2];
const controlLabels=["Pause Altr","Review Memory","Edit Memory","Delete Memory","Approval History","Connected Accounts","Activity Log","Emergency Stop","Clear All Data"];

function Brand(){return <span className={styles.brand}>Altr <i><b/></i></span>}
function Reveal({children,className="",delay=0}:{children:React.ReactNode;className?:string;delay?:number}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:26}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:"-80px"}} transition={{duration:.65,delay,ease:[.16,1,.3,1]}}>{children}</motion.div>}
function Eyebrow({children,dark=false}:{children:React.ReactNode;dark?:boolean}){return <p className={dark?styles.eyebrowDark:styles.eyebrow}>{children}</p>}

export function SecondPresenceLanding(){
 const [lang,setLang]=useLang("UA"); const t=text[lang]; const reduced=useReducedMotion(); const [menu,setMenu]=useState(false); const [signed,setSigned]=useState(false); const [step,setStep]=useState(0); const [mode,setMode]=useState(1); const [notice,setNotice]=useState(""); const {scrollYProgress}=useScroll(); const progress=useSpring(scrollYProgress,{stiffness:100,damping:25});
 useEffect(()=>{let active=true;getCurrentProfile().then(p=>{if(active)setSigned(Boolean(p))});return()=>{active=false}},[]);
 useEffect(()=>{if(reduced){setStep(t.demo.steps.length);return}if(step>=t.demo.steps.length)return;const id=window.setTimeout(()=>setStep(v=>v+1),step?850:650);return()=>window.clearTimeout(id)},[step,reduced,t.demo.steps.length,lang]);
 const cta=signed?"/dashboard":"/auth?mode=register"; const login=signed?"/dashboard":"/auth?mode=login";
 const navIds=["product","how","memory","autopilot","security"];
 const replay=()=>{setNotice("");setStep(reduced?t.demo.steps.length:0)};
 return <main id="top" className={styles.page}>
  <div className={styles.identityThread} aria-hidden="true"><motion.span style={{scaleY:progress}}/><small>Messages</small><small>Memory</small><small>Decisions</small><small>Voice</small><small>Actions</small></div>
  <header className={styles.header}><nav><a href="#top"><Brand/></a><div className={styles.desktopNav}>{t.nav.map((label,i)=><a key={label} href={`#${navIds[i]}`}>{label}</a>)}</div><div className={styles.headerActions}><div className={styles.lang}>{(["EN","UA"] as Lang[]).map(code=><button key={code} aria-pressed={lang===code} onClick={()=>setLang(code)}>{code}</button>)}</div><Link className={styles.login} href={login}>{t.login}</Link><Link className={styles.headerCta} href={cta}>{t.create}</Link><button className={styles.menuButton} onClick={()=>setMenu(v=>!v)} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></nav><AnimatePresence>{menu&&<motion.div className={styles.mobileMenu} initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{t.nav.map((label,i)=><a key={label} href={`#${navIds[i]}`} onClick={()=>setMenu(false)}>{label}<ArrowRight/></a>)}<Link href={cta}>{t.create}<ArrowRight/></Link></motion.div>}</AnimatePresence></header>

  <section id="product" className={styles.hero}><Reveal className={styles.heroCopy}><Eyebrow>ALTR — SECOND PRESENCE</Eyebrow><h1><span>{t.hero[0]}</span><em>{t.hero[1]}</em></h1><p>{t.subtitle}</p><div className={styles.actions}><Link href={cta} className={styles.primary}>{t.create}<ArrowRight/></Link><a href="#demo" className={styles.secondary}><Play/>{t.action}</a></div><small className={styles.trust}><b/>{t.trust}</small></Reveal>
   <Reveal className={styles.demo} delay={.08}><div id="demo" className={styles.demoTop}><span>LIVE PRODUCT DEMO</span><button onClick={replay}><RotateCcw/>{t.demo.replay}</button></div><article className={styles.incoming}><small>Incoming message</small><time>09:42</time><p>{t.demo.incoming}</p></article><div className={styles.steps}>{t.demo.steps.map((label,i)=><div key={label} className={i<step?styles.done:i===step?styles.active:""}><b>{i<step?<Check/>:String(i+1).padStart(2,"0")}</b><span>{label}</span></div>)}</div>{step>=t.demo.steps.length&&<motion.div className={styles.demoResult} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}><aside><small>Relevant context</small><p>{t.demo.context}</p></aside><section><small>Suggested response</small><p>{t.demo.reply}</p></section><div className={styles.demoButtons}><button className={styles.primary} onClick={()=>setNotice("Approved by you")}><Check/>{t.demo.approve}</button><button className={styles.secondary} onClick={()=>setNotice("Opened for editing")}><Edit3/>{t.demo.edit}</button><button onClick={()=>setNotice("Draft ignored")}>{t.demo.ignore}</button></div>{notice&&<small className={styles.notice}><b/>{notice}</small>}</motion.div>}</Reveal>
  </section>

  <section className={styles.section}><div className={styles.twoCol}><Reveal><Eyebrow>SECOND PRESENCE</Eyebrow><h2 className={styles.editorial}><span>{t.presence[0]}</span><em>{t.presence[1]}</em></h2><p className={styles.body}>{t.presenceBody}</p></Reveal><Reveal className={styles.statusPanel} delay={.08}><header><span>ALTR STATUS</span><strong><b/>Online</strong></header>{t.status.map((item,i)=><div key={item}><small>0{i+1}</small><p>{item}</p>{i===3?<ShieldCheck/>:<Activity/>}</div>)}</Reveal></div></section>

  <section id="memory" className={`${styles.section} ${styles.soft}`}><Reveal className={styles.heading}><Eyebrow>CONTINUOUS MEMORY</Eyebrow><h2>{t.memoryTitle}</h2></Reveal><div className={styles.memoryGrid}><Reveal className={styles.contact}><header><span>DK</span><div><h3>Daniel Kovalenko</h3><p>Supplier · China</p></div><b>94%</b></header>{memories.map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</Reveal><Reveal className={styles.insight} delay={.08}><Sparkles/><small>ALTR INSIGHT</small><blockquote>Daniel usually answers faster when the request includes exact quantities and a clear deadline.</blockquote><p>{t.memoryNote}</p><Link href="/memory">Open Memory<ArrowRight/></Link></Reveal></div></section>

  <section className={`${styles.section} ${styles.dark}`}><Reveal className={styles.darkHeading}><Eyebrow dark>YOUR VOICE</Eyebrow><h2><span>{t.voice[0]}</span><em>{t.voice[1]}</em></h2></Reveal><div className={styles.voiceGrid}>{[["Generic AI","Thank you for your message. I will review the information shortly."],["Usual response","Got it. I’ll check everything today and get back to you."],["Altr","Got it. I’ll review the updated prices today and send you a decision before 18:00."]].map(([label,body],i)=><Reveal key={label} className={i===2?styles.voiceActive:styles.voice} delay={i*.05}><small>{label}</small><p>“{body}”</p>{i===2&&<footer><span>Context</span><span>Specificity</span><span>Voice</span></footer>}</Reveal>)}</div><Reveal><p className={styles.voiceNote}>{t.voiceNote}</p></Reveal></section>

  <section id="autopilot" className={styles.section}><div className={styles.twoCol}><Reveal><Eyebrow>CONTROLLED AUTONOMY</Eyebrow><h2 className={styles.autopilotTitle}>{t.autopilot}</h2><div className={styles.modeTabs}>{t.modes.map((label,i)=><button key={label} aria-pressed={mode===i} onClick={()=>setMode(i)}>{label}</button>)}</div><AnimatePresence mode="wait"><motion.p key={mode} className={styles.modeBody} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}}>{t.modeBodies[mode]}</motion.p></AnimatePresence></Reveal><Reveal className={styles.rules} delay={.08}><div><header><Check/>Can reply automatically</header>{autoYes.map(x=><p key={x}><b/>{x}</p>)}</div><div><header><ShieldCheck/>Always requires approval</header>{autoNo.map(x=><p key={x}><i/>{x}</p>)}</div></Reveal></div></section>

  <section id="how" className={`${styles.section} ${styles.soft}`}><Reveal className={styles.heading}><Eyebrow>HOW IT WORKS</Eyebrow><h2>{t.howTitle}</h2></Reveal><div className={styles.process}>{t.how.map((title,i)=><Reveal key={title} className={styles.processRow} delay={i*.04}><span>0{i+1}</span><div><h3>{title}</h3><p>{["Connect selected platforms and import approved conversations.","Altr identifies communication patterns, relationships and recurring decisions.","Relevant context is retrieved before a response or next action is proposed.","You approve, edit or reject important actions.","Approved decisions improve future suggestions and strengthen the personal model."][i]}</p></div><ArrowRight/></Reveal>)}</div></section>

  <section id="security" className={styles.section}><div className={styles.securityGrid}><Reveal><Eyebrow>ALWAYS UNDER YOUR CONTROL</Eyebrow><h2 className={styles.editorial}><span>{t.security[0]}</span><em>{t.security[1]}</em></h2><p className={styles.body}>{t.securityBody}</p><div className={styles.controls}>{controlLabels.map((label,i)=>{const Icon=controls[i];return <button key={label}><Icon/>{label}</button>})}</div></Reveal><Reveal className={styles.logPanel} delay={.08}><header><span>ACTIVITY LOG</span><strong><b/>Live</strong></header>{[["09:42","Draft prepared"],["09:44","Reply approved by user"],["09:44","Memory updated"],["10:12","Automatic reply sent"],["11:06","Rule changed"],["11:18","Integration paused"]].map(([time,event],i)=><div key={time+event}><time>{time}</time><b>{i+1}</b><p>{event}</p></div>)}</Reveal></div></section>

  <section className={`${styles.section} ${styles.dashboardSection}`}><Reveal className={styles.darkHeading}><Eyebrow dark>PRODUCT PREVIEW</Eyebrow><h2>{t.dashboard}</h2><p>Not another chatbot. A focused operating layer for conversations, people, decisions and rules.</p></Reveal><Reveal className={styles.dashboard}><aside><Brand/>{["Now","Conversations","Memory","People","Rules","Activity","Settings"].map((x,i)=><span className={i===0?styles.selected:""} key={x}>{x}</span>)}<footer><small>ALTR STATUS</small><strong><b/>Active</strong></footer></aside><main><header><small>NOW</small><h3>Decisions that need attention</h3></header>{[["Needs approval","Reply to Daniel regarding new pricing"],["Handled automatically","Confirmed meeting with Anna"],["Memory updated","Added delivery preference for Sophia"],["Potential conflict","Two promises have overlapping deadlines"]].map(([a,b],i)=><article key={b} className={i===3?styles.warning:""}><small>{a}</small><h4>{b}</h4><p>{i===0?"Review before 18:00":"Context and audit history available"}</p><ArrowRight/></article>)}</main><section><small>WHY THIS ACTION</small>{[["Person","Daniel Kovalenko"],["Relationship","Supplier · 2 years"],["Current topic","New product pricing"],["Open commitment","Updated proposal"],["Relevant memories","6 matched"],["Confidence","92%"]].map(([a,b])=><div key={a}><small>{a}</small><strong>{b}</strong></div>)}</section></Reveal></section>

  <section className={styles.section}><Reveal className={styles.heading}><Eyebrow>INTEGRATIONS</Eyebrow><h2>{t.integrations}</h2><p>Conversation imports are available today. Direct sync appears only when an integration is production-ready.</p></Reveal><div className={styles.integrations}>{[[Send,"Telegram","Import available"],[Mail,"Gmail","Import available"],[CalendarDays,"Google Calendar","Coming soon"],[Link2,"Future integrations","Coming soon"]].map(([Icon,name,state],i)=>{const C=Icon as typeof Send;return <Reveal key={String(name)} className={styles.integration} delay={i*.04}><C/><div><strong>{String(name)}</strong><span>{String(state)}</span></div></Reveal>})}</div></section>

  <section id="pricing" className={`${styles.section} ${styles.soft}`}><Reveal className={styles.heading}><Eyebrow>PRICING</Eyebrow><h2>{t.pricing}</h2><p>Checkout and paid access continue through the existing Lemon Squeezy billing flow.</p></Reveal><div className={styles.pricing}><Reveal className={styles.personal}><small>PERSONAL</small><div><del>$30</del><strong>$20</strong><span>{t.month}</span></div><ul>{["One Personal Altr","Core AI memory","Conversation imports","Communication style learning","Context-aware reply drafts","Manual approval controls","Memory management"].map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href="/pricing" className={styles.secondary}>{t.personal}<ArrowRight/></Link></Reveal><Reveal className={styles.operator} delay={.08}><header><small>OPERATOR</small><Sparkles/></header><div><del>$60</del><strong>$40</strong><span>{t.month}</span></div><ul>{["Three customizable Altrs","Advanced AI memory","Separate roles and identities","Advanced approval rules","Controlled autopilot","Priority processing","Future integrations access"].map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href="/pricing" className={styles.primary}>{t.operator}<ArrowRight/></Link></Reveal></div></section>

  <section className={styles.final}><Reveal><h2><span>{t.final[0]}</span><em>{t.final[1]}</em></h2><p>{t.finalBody}</p><Link href={cta} className={styles.primary}>{t.create}<ArrowRight/></Link><small>{t.remain}</small></Reveal></section>
  <footer className={styles.footer}><div><Brand/><p>A second presence, built from the first.</p></div><nav><a href="#product">Product</a><a href="#how">How it works</a><a href="#memory">Memory</a><a href="#autopilot">Autopilot</a><a href="#pricing">Pricing</a><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Use</Link><Link href="/cookies">Cookie Policy</Link><Link href="/data-deletion">Data Deletion</Link></nav><p>© 2026 Altr</p></footer>
 </main>
}
