import { MemoryItem } from "@/components/memory/types";

export const initialMemoryItems: MemoryItem[] = [
  { id: "mem_001", category: "Communication Style", title: "Short direct replies", description: "The user usually writes concise replies and avoids unnecessary wording.", confidence: 92, lastUpdated: "2026-07-10", source: "Telegram messages", isActive: true },
  { id: "mem_002", category: "Communication Style", title: "Low formality", description: "Avoids overly formal phrases and prefers natural, modern language.", confidence: 88, lastUpdated: "2026-07-10", source: "Email threads", isActive: true },
  { id: "mem_003", category: "Communication Style", title: "Calm confidence", description: "Keeps a calm but confident tone, especially when confirming decisions.", confidence: 86, lastUpdated: "2026-07-09", source: "Client conversations", isActive: true },
  { id: "mem_004", category: "Communication Style", title: "Practical response rhythm", description: "Usually responds quickly and focuses on the next practical action.", confidence: 82, lastUpdated: "2026-07-08", source: "Imported conversations", isActive: true },
  { id: "mem_005", category: "Frequent Phrases", title: "Sounds good", description: "A short confirmation used when the proposed direction is acceptable.", confidence: 95, lastUpdated: "2026-07-10", source: "Telegram messages", isActive: true },
  { id: "mem_006", category: "Frequent Phrases", title: "I’ll check and get back to you", description: "Used when a detail needs verification before a final answer.", confidence: 91, lastUpdated: "2026-07-10", source: "Email threads", isActive: true },
  { id: "mem_007", category: "Frequent Phrases", title: "Let’s do it", description: "A concise phrase used to approve a clear next step.", confidence: 89, lastUpdated: "2026-07-09", source: "Team messages", isActive: true },
  { id: "mem_008", category: "Frequent Phrases", title: "Send me the details", description: "Often requests the missing context before moving forward.", confidence: 87, lastUpdated: "2026-07-08", source: "Client conversations", isActive: false },
  { id: "mem_009", category: "Important Context", title: "Client and team communication", description: "The user works across client conversations and short task-focused team messages.", confidence: 93, lastUpdated: "2026-07-10", source: "Multiple sources", isActive: true },
  { id: "mem_010", category: "Important Context", title: "Commercial details matter", description: "Prices, delivery dates, timelines and final decision details appear frequently.", confidence: 90, lastUpdated: "2026-07-09", source: "Email threads", isActive: true },
  { id: "mem_011", category: "Important Context", title: "Practical answers first", description: "Prefers actionable answers over long explanations or abstract discussion.", confidence: 85, lastUpdated: "2026-07-08", source: "Imported conversations", isActive: true },
  { id: "mem_012", category: "Relationships", title: "Client tone", description: "With clients, communication should be formal enough, clear and reliable.", confidence: 91, lastUpdated: "2026-07-10", source: "Client conversations", isActive: true },
  { id: "mem_013", category: "Relationships", title: "Team tone", description: "With the team, messages are short, direct and centered on tasks.", confidence: 94, lastUpdated: "2026-07-09", source: "Team messages", isActive: true },
  { id: "mem_014", category: "Relationships", title: "Supplier priorities", description: "When speaking with suppliers, price, timing and precise details matter most.", confidence: 84, lastUpdated: "2026-07-08", source: "Email threads", isActive: true },
  { id: "mem_015", category: "Typical Decisions", title: "Verify before confirming", description: "Confirms only after checking the final details and possible dependencies.", confidence: 96, lastUpdated: "2026-07-10", source: "Multiple sources", isActive: true },
  { id: "mem_016", category: "Typical Decisions", title: "Safe practical choices", description: "Prefers reliable and practical decisions over risky or unclear options.", confidence: 88, lastUpdated: "2026-07-09", source: "Imported conversations", isActive: true },
  { id: "mem_017", category: "Typical Decisions", title: "Ask for context", description: "Requests more information when the available context is not enough for a decision.", confidence: 90, lastUpdated: "2026-07-09", source: "Telegram messages", isActive: true },
  { id: "mem_018", category: "Typical Decisions", title: "No promises before checks", description: "Avoids making commitments until price, timing and feasibility are confirmed.", confidence: 93, lastUpdated: "2026-07-08", source: "Email threads", isActive: true },
];
