"use client";

import { BrainCircuit, ChevronRight, Database, Gauge } from "lucide-react";
import { assistantsCopy, optionLabel } from "./copy";
import { AssistantConfig, AssistantsLang } from "./types";

export function AssistantCard({ assistant, lang, selected, onConfigure }: { assistant: AssistantConfig; lang: AssistantsLang; selected: boolean; onConfigure: () => void }) {
  const t=assistantsCopy[lang]; const twin=assistant.type==="personal_twin";
  return <article className={`assistant-card ${selected?"assistant-card-selected":""}`}><div className="assistant-scan" /><div className="relative"><div className="flex items-start justify-between gap-4"><span className="assistant-index">{assistant.id==="assistant_twin"?"A-01":assistant.id==="assistant_operator"?"A-02":"A-03"}</span><span className={`assistant-card-status ${assistant.status==="active"?"assistant-card-status-active":""}`}><i />{assistant.status==="active"?t.active:t.draft}</span></div><div className="mt-9 flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-[14px] border border-cyan-100/[.11] bg-cyan-200/[.04]"><BrainCircuit className="h-5 w-5 text-cyan-100/60" /></span><div><p className="text-[10px] uppercase tracking-[.15em] text-cyan-100/40">{twin?t.twinType:t.customType}</p><h2 className="mt-1 text-2xl font-medium tracking-[-.04em]">{assistant.name}</h2></div></div><p className="mt-5 min-h-[72px] text-sm leading-6 text-white/39">{assistant.description}</p><span className="mt-4 inline-flex rounded-full border border-cyan-100/[.1] bg-cyan-200/[.035] px-3 py-1.5 text-[9px] uppercase tracking-[.14em] text-cyan-100/55">{twin?t.learns:t.customizable}</span><div className="mt-7 grid grid-cols-2 gap-2"><div className="assistant-micro-stat"><Gauge /><span><small>Autonomy</small>{optionLabel(assistant.autonomyLevel,lang)}</span></div><div className="assistant-micro-stat"><Database /><span><small>Memory</small>{assistant.memoryAccess.length} scopes</span></div></div><button onClick={onConfigure} className="future-button mt-7 flex w-full items-center justify-center gap-2 rounded-full px-5 py-3 text-xs">{t.configure}<ChevronRight className="h-3.5 w-3.5" /></button></div></article>;
}
