"use client";

import { AlertTriangle, Check, RotateCcw, Save, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { autonomyOptions, customBoundaryOptions, customDataSources, customPersonalityOptions, customTaskOptions, customToneOptions, responseOptions, twinBoundaryOptions, twinMemoryOptions, twinPersonalityOptions, twinToneOptions } from "@/lib/assistantData";
import { assistantsCopy, optionLabel } from "./copy";
import { AssistantConfig, AssistantsLang } from "./types";
import { AssistantToggle } from "./AssistantToggle";

function ChoiceList({ values, selected, lang, onToggle }: { values: string[]; selected: string[]; lang: AssistantsLang; onToggle: (value:string)=>void }) {
  return <div className="assistant-choice-grid">{values.map(value=><button type="button" key={value} onClick={()=>onToggle(value)} className={selected.includes(value)?"assistant-choice-active":""}><span>{selected.includes(value)&&<Check className="h-3 w-3" />}</span>{optionLabel(value,lang)}</button>)}</div>;
}

export function AssistantConfigPanel({ assistant, lang, onSave, onReset }: { assistant: AssistantConfig; lang: AssistantsLang; onSave: (value:AssistantConfig)=>void; onReset:()=>void }) {
  const [draft,setDraft]=useState(assistant); const [saved,setSaved]=useState(false); const t=assistantsCopy[lang]; const twin=draft.type==="personal_twin";
  useEffect(()=>{setDraft(assistant);setSaved(false)},[assistant]);
  const toggleArray=(key:"memoryAccess"|"tasks"|"boundaries"|"dataSources",value:string)=>setDraft(current=>({...current,[key]:current[key].includes(value)?current[key].filter(item=>item!==value):[...current[key],value]}));
  const save=()=>{onSave({...draft,status:"active",updatedAt:new Date().toISOString().slice(0,10)});setSaved(true);setTimeout(()=>setSaved(false),1700)};
  return <section id="assistant-config" className="assistant-config-panel"><div className="flex flex-col justify-between gap-5 border-b border-white/[.06] pb-6 sm:flex-row sm:items-start"><div><p className="data-label">ASSISTANT CONTROL / {assistant.id.toUpperCase()}</p><h2 className="mt-3 text-3xl font-medium tracking-[-.045em]">{t.configTitle}: {assistant.name}</h2><p className="mt-2 text-sm text-white/32">{t.configSubtitle}</p></div><div className="flex gap-2"><button onClick={onReset} className="glass-button inline-flex items-center gap-2 rounded-full px-4 py-2.5 text-xs"><RotateCcw className="h-3.5 w-3.5" />{t.reset}</button><button onClick={save} className="future-button inline-flex items-center gap-2 rounded-full px-4 py-2.5 text-xs"><Save className="h-3.5 w-3.5" />{saved?t.saved:t.save}</button></div></div>
    <div className="mt-7 grid gap-6 lg:grid-cols-2"><div className="space-y-5"><label className="settings-field"><span>{t.labels.name}</span><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} /></label><label className="settings-field"><span>{t.labels.role}</span><input value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})} /></label><label className="settings-field"><span>{t.labels.description}</span><textarea rows={4} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} /></label></div><div className="grid content-start gap-5 sm:grid-cols-2"><label className="settings-field"><span>{t.labels.tone}</span><select value={draft.tone} onChange={e=>setDraft({...draft,tone:e.target.value})}>{(twin?twinToneOptions:customToneOptions).map(value=><option key={value} value={value}>{optionLabel(value,lang)}</option>)}</select></label><label className="settings-field"><span>{t.labels.personality}</span><select value={draft.personality} onChange={e=>setDraft({...draft,personality:e.target.value})}>{(twin?twinPersonalityOptions:customPersonalityOptions).map(value=><option key={value} value={value}>{optionLabel(value,lang)}</option>)}</select></label><label className="settings-field"><span>{t.labels.response}</span><select value={draft.responseLength} onChange={e=>setDraft({...draft,responseLength:e.target.value})}>{responseOptions.map(value=><option key={value} value={value}>{optionLabel(value,lang)}</option>)}</select></label><label className="settings-field"><span>{t.labels.autonomy}</span><select value={draft.autonomyLevel} onChange={e=>setDraft({...draft,autonomyLevel:e.target.value as AssistantConfig["autonomyLevel"]})}>{autonomyOptions.map(value=><option key={value} value={value}>{optionLabel(value,lang)}</option>)}</select></label></div></div>
    <div className="mt-7 grid gap-4 lg:grid-cols-2"><div className="assistant-setting-block"><div className="flex items-start justify-between gap-4"><div><p className="data-label">{t.labels.memory}</p><h3 className="mt-2 text-lg font-medium">{twin?"Personal memory scopes":"Context access"}</h3></div><span className="assistant-access-count">{draft.memoryAccess.length} enabled</span></div><div className="mt-5"><ChoiceList values={twin?twinMemoryOptions:customDataSources} selected={draft.memoryAccess} lang={lang} onToggle={value=>toggleArray("memoryAccess",value)} /></div></div><div className="assistant-setting-block"><div className="flex items-center justify-between gap-4"><div><p className="data-label">{t.labels.learning}</p><h3 className="mt-2 text-lg font-medium">Behavior learning</h3></div><AssistantToggle active={draft.learningEnabled} onChange={()=>setDraft({...draft,learningEnabled:!draft.learningEnabled})} label={t.labels.learning} /></div><p className="mt-4 text-xs leading-5 text-white/30">{draft.learningEnabled?"The assistant can refine its behavior from approved interactions.":"Learning is disabled. Current configuration stays unchanged."}</p></div></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="assistant-setting-block"><p className="data-label">{t.labels.tasks}</p><h3 className="mt-2 text-lg font-medium">Assigned work</h3><div className="mt-5"><ChoiceList values={customTaskOptions} selected={draft.tasks} lang={lang} onToggle={value=>toggleArray("tasks",value)} /></div></div><div className="assistant-setting-block"><p className="data-label">{t.labels.boundaries}</p><h3 className="mt-2 text-lg font-medium">Hard limits</h3><div className="mt-5"><ChoiceList values={twin?twinBoundaryOptions:customBoundaryOptions} selected={draft.boundaries} lang={lang} onToggle={value=>toggleArray("boundaries",value)} /></div></div></div>
    {!twin&&<div className="assistant-setting-block mt-4"><p className="data-label">{t.labels.sources}</p><div className="mt-5"><ChoiceList values={customDataSources} selected={draft.dataSources} lang={lang} onToggle={value=>toggleArray("dataSources",value)} /></div></div>}
    {twin&&<div className="assistant-warning mt-4"><AlertTriangle className="h-5 w-5 flex-none" /><div><strong>Human control required</strong><p>{t.twinWarning}</p></div><ShieldCheck className="ml-auto hidden h-5 w-5 flex-none text-cyan-100/35 sm:block" /></div>}
  </section>;
}
